### ISSUE TITLE
Need to re-think initialization sequence

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-GitWriter#15]
There are a few issues that need fixing:

1. Currently [authentication is needed to load the app files](https://github.com/cwrc/CWRC-GitWriter/blob/master/src/js/app.js#L4) but the writer [still tries to initialize anyways](https://github.com/cwrc/CWRC-GitWriter/blob/master/src/html/index.html#L13). This causes a error in the console. Could we initialize the app and then try to authenticate?
1. The [dialogs](https://github.com/cwrc/cwrc-git-dialogs) rely on bootstrap, but the bootstrap CSS doesn't get loaded until [partway through the writer's initialization process](https://github.com/cwrc/CWRC-WriterBase/blob/master/src/js/dialogs/cwrcDialogBridge.js#L10). The dialog requires the CSS to already be loaded before it's shown. This wasn't an issue before because [the CSS was linked in the HTML](https://github.com/cwrc/CWRC-GitWriter/blob/c15b96f9497d9261d8e3b6286a572e1ba1164df1/src/html/index.html#L13), but now we're adding all CSS dynamically.

**Comment by jchartrand** [comment]
Could the first problem be fixed by moving the code from index.html (in the script tag) into app.js, so that app.js becomes:

window.CWRCWriterStorageDialogs = require('cwrc-git-dialogs');  // could this be moved out of window, and into a local variable, using const, or let, since it would no longer have to be passed into the javascript running in the script tag?

// only continue loading the cwrcWriter if the user has authenticated with github
if (window.CWRCWriterStorageDialogs.authenticate()) {

    	let viaf = require('viaf-entity-lookup')
   	let dbpedia = require('dbpedia-entity-lookup');
   	let wikidata = require('wikidata-entity-lookup');
    	let getty = require('getty-entity-lookup');
    	window.CWRCWriterDialogs = require('cwrc-public-entity-dialogs');  // could this then be moved out of the window, and into a variable using const or let?

    	window.CWRCWriterDialogs.registerEntitySources({
        	people: (new Map()).set('viaf', viaf).set('wikidata', wikidata).set('getty', getty).set('dbpedia', dbpedia),
        	places: (new Map()).set('viaf', viaf).set('dbpedia', dbpedia).set('wikidata', wikidata),
        	organizations: (new Map()).set('viaf', viaf).set('wikidata', wikidata).set('dbpedia', dbpedia),
        	titles: (new Map()).set('viaf', viaf).set('wikidata', wikidata).set('dbpedia', dbpedia),
   	 })

	let config = require('./config.js');
	let CWRCWriter = require('cwrc-writer-base’);
    
    	window.CWRCWriterConfig = config;  // would this still be needed?
    	window.CWRCWriter = CWRCWriter; // or this?

	
	config.container = 'cwrcWriterContainer';
	config.modules = {
		west: ['structure','entities'],
		south: ['selection', 'validation']
	};
	config.entityLookupDialogs = CWRCWriterDialogs;
	config.storageDialogs = CWRCWriterStorageDialogs;
	var writer = new CWRCWriter(config);
	writer.showLoadDialog();


}

 This would keep the app from trying to initialize, because the app would only try to initialize if the authentication call returned ‘true’.  The authentication call never actually returns ‘false’ because if it is false, i.e,. the user hasn’t yet authenticated, then the user is redirected to the Github auth page.

I’m guessing you moved this config stuff out of app.js, where we had it for a while, and into the index.html page, because of something to do with the Islandora version?  But, I don’t think there is anything stopping us from doing it all in app.js for the GitWriter?
 
And for the second problem, it sounds like we just need to wait to show the dialog (i.e., wait to call writer.showLoadDialog()) until the writer has finished initializing, and I think you've already got an event for that?

**Comment by ajmacdonald** [comment]
Thanks @jchartrand 
These [changes](https://github.com/cwrc/CWRC-DevGitWriter/commit/d0ef32d82ddfd2358428cf4639bbc041947af298) are in place now on dev

**Comment by jchartrand** [comment]
May I push a couple changes up to CWRC-DevGitWriter, and try deploying to the dev DAIR server?

**Comment by jchartrand** [comment]
I just redeployed, but when I try to load it I get the same error we had yesterday:



but I don’t see that file in the build directory after I build the CWRC-DevGitWriter?

**Comment by jchartrand** [comment]
Now I’m having a problem with the CWRC-PublicEntityDialogs.  I get the error:’



which I’m guessing is something to do with how bootstrap is tied in to jquery, and possibly something to do with the lines you added:

https://github.com/cwrc/CWRC-PublicEntityDialogs/blob/0f61432aaf2f6cb4539272f6cf0ec94d3b529171/src/index.js#L1-L5

That code does run fine using the tests though (when running ‘npm test’ on the CWRC-PublicEntityDialogs code).  So, maybe there is something
going on outside the CWRC-PublicEntityDialogs that is changing the version of jquery bound to $, and so by the time the call is made to get the modal, i.e.,

$(‘#cwrc-entity-lookup).modal

the version of jquery bound to $ has switched and no longer has bootstrap tied in?

Any ideas?  Could I modify the CWRC-PublicEntityDialogs code to not use $ for jquery, and instead use some other variable (just within this CWRC-PublicEntityDialogs module)?  Or would that interfere with other code elsewhere?  How are you attaching bootstrap to jquery elsewhere?

**Comment by ajmacdonald** [comment]
@jchartrand I can't see the error you've pasted into your comment

**Comment by jchartrand** [comment]
I don't know why it sometimes shows the images, sometimes not.  Anyhow, here it is:

![pastedgraphic-6](https://user-images.githubusercontent.com/547165/35474808-62af352e-0361-11e8-8d53-7434f4051f41.png)

**Comment by ajmacdonald** [comment]
This [commit](https://github.com/cwrc/CWRC-DevGitWriter/commit/fb7c98170d5d65ae8105aac1213dca4997d2584d) addresses that
