### ISSUE TITLE
Saving to a repo that I do not own does not work.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#16]
I tried to save a change to a Git-Writer repo created by Susan and I was unable to. 
I got an error message:

![Screen Shot 2018-02-06 at 10.53.42 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/e8ee37f5-ce95-4201-8f94-b9024b5eb9d4)

**Comment by jchartrand** [comment]
It is likely that you aren’t a collaborator on Susan’s repo.  If so, the real problem is that we need to tell the user that when they first try to load the repository, e.g., ‘You may load the document in this repository, but you don’t have rights to save any changes back to the original repository.  To do so, please ask the owner of the repository, SusanBrown, to add you as a collaborator.  You may still load the document, and save it, including any changes you might make, to a new repository.’

**Comment by SusanBrown** [comment]
Mihaela, do we have any gitWriter user documentation at this point? What James says makes sense to me, and I think would to other people used to github, so if we could just add note of this to the documentation 

I removed the setting "Restrict editing to collaborators only" from TestingPoetryJan 2018. Could you please try editing that file?

**Comment by ilovan** [comment]
Still can't save to TestingPoetryJan 2018.
Can't save to Testing-Keywords-Feb-10 either, but with a different error message:
<img width="1412" alt="screen shot 2018-02-12 at 10 28 13 pm" src="https://user-images.githubusercontent.com/6600070/36134767-37ed7586-1044-11e8-8e37-8e55b1f4cabe.png">

**Comment by jchartrand** [comment]
Can you add me as a collaborator to Testing-Keywords-Feb-10?
And could you take a screen shot of where you set "Restrict editing to collaborators only" for TestingPoetryJan 2108?  I don't see that option in my Github interface.

**Comment by SusanBrown** [comment]
I was able to save to your Old Possum's Book of Practical Cats collection, Mihaela. 

The message asking me if I wanted to save to your repo or make my own was nice.

James, I just added you to Testing Keywords Feb 10. Mihaela, it looks like you didn't accept the invitation to collaborate, so perhaps if you accept it you will be able to save.  Here's the invite link: https://github.com/SusanBrown/Testing-keywords-Feb-10/invitations

![image](https://user-images.githubusercontent.com/545952/36804146-b0f0068e-1c87-11e8-89f3-90bcaae27e61.png)

James, below is a screenshot of where you can restrict the editing to collaborators. (As an aside, Mihaela, I note that we can turn issues off. We might want to do that in a number of the CWRC-Writer repositories to keep the issues streamlined to just a few and to reduce the number of places where the feedback forms need to be set up.)

![image](https://user-images.githubusercontent.com/545952/36804265-0aee25f8-1c88-11e8-8331-fd78bd5213a1.png)

**Comment by jchartrand** [comment]
The 'Restrict Editing to Collaborators Only' only applies to wikis (I think, but it is awfully vague if so) :

 'https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by ilovan** [comment]
I read it the same way, James. I also confirm that once I accepted the collaboration invitation, I was able to edit Susan's repository in the production Git-Writer, so I am going to close this issue.

**Comment by jchartrand** [comment]
I still think we should tell the user, when they open another users repo, that they need to be added as a collaborator in order to save back to the repo, i.e., the text that I proposed earlier:

‘You may load the document in this repository, but you don’t have rights to save any changes back to the original repository.  To do so, please ask the owner of the repository, SusanBrown, to add you as a collaborator.  You may still load the document, and save it, including any changes you might make, to a new repository.’

If this change should be made, perhaps it should go into a new GitHub issue.
