### ISSUE TITLE
Enable https on showcase/production version of the server at http://208.75.74.217/

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#5]
According to Jeff, https should be activated (by the server admin). At present, he says it would be fairly easy for someone to gain access to a cwrc-writer user's github account.

**Comment by jchartrand** [comment]
Yes. I’ll look into enabling https next week, but so we all understand the problem, and so we can document it, how would someone gain access without https?  You can reply outside of the github issue so that the risk isn’t made public.

**Comment by ilovan** [comment]
This is all we got from Jeff on Friday afternoon before he left on his Library sprint: 

> Suggestion, https should be activated (by the server admin). At present, I think it would be fairly easy for someone to gain access to a cwrc-writer user's github account.

**Comment by jchartrand** [comment]
I’ve got https enabled now on the new DAIR development instance, but it’s causing some mixed content errors that andrew and I will have to sort out before I can enable it on the production server.  We’re also sorting out how to now handle the two streams of code - dev and prod.

**Comment by SusanBrown** [comment]
Thanks for the update. Great progress.


On Dec 19, 2017, at 10:08 AM, James Chartrand <notifications@github.com<mailto:notifications@github.com>> wrote:

I’ve got https enabled now on the new DAIR development instance, but it’s causing some mixed content errors that andrew and I will have to sort out before I can enable it on the production server. We’re also sorting out how to now handle the two streams of code - dev and prod.

**Comment by jchartrand** [comment]
https is now enabled on both dev and prod.  note that both are using a locally generated certificate so you'll get a warning in some browsers, and may have to add the sites as exceptions.  To avoid these warning we'd need certificates from a trusted authority.  I don't know if CWRC has existing certificates?

**Comment by ilovan** [comment]
We are using [Let's encrypt](https://letsencrypt.org/). Could you install the same on the two servers?

**Comment by jchartrand** [comment]
Apparently Let's Encrypt has got some security issue (as of today) that's causing a problem:

https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983

I'll try it again tomorrow and if they aren't back up then I'll use the workaround mentioned in that post.

**Comment by SusanBrown** [comment]
@jchartrand Was it still down yesterday? Could you please check again first thing this morning and try to get it up asap? I realize belatedly (and I do apologize but have had some real strains lately that left me with no time to think of this in advance) that I will be talking about this in my paper here at U Virginia tomorrow and it would be **much** better if the http error were fixed as people will likely want to take a look at gitwriter.

**Comment by jchartrand** [comment]
Yes, letsEncrypt still had the same problem yesterday, and today.

I’ve used the workaround on the development version, which now seems to be working:

https://dev-cwrc-writer.cwrc.ca <https://dev-cwrc-writer.cwrc.ca/>

Note that if you try to access that site using the IP address (i.e., https://208.75.74.225 <https://208.75.74.225/>), then the certificate won’t match, and you’ll get an error.

I’ve also re-enabled the http version on dev:

http://dev-cwrc-writer.cwrc.ca <http://dev-cwrc-writer.cwrc.ca/>  which will also work with the IP address (http://208.75.74.225 <http://208.75.74.225/>)

For a demo, the http version might be the better choice, since I don’t think anyone has done very much testing of the HTTPS version.

I’ll do the production in a moment.

**Comment by jchartrand** [comment]
I've now setup a LetsEncrypt certificate on the prod version:

https://cwrc-writer.cwrc.ca

and re-enabled http:

http://cwrc-writer.cwrc.ca

Again, for a demo, http is probably the better choice.

**Comment by jchartrand** [comment]
hmmm, just testing this, and discovered another problem which I'm working on.

However, the http versions should work.

**Comment by jchartrand** [comment]
So, the https versions won't now work until I fix a bigger problem.

Use the http versions for now.

**Comment by jchartrand** [comment]
I'll continue to work on the problem, but won't make any more changes to either the prod or dev servers until after your demo.  Again, the https versions won't work.  The http versions will.

**Comment by jchartrand** [comment]
So yet another problem has emerged.

We make HTTP calls to three of our entity sources (getty, viaf, dbpedia), and HTTPS to wikidata.

Just like the problem we have with the http schema and css uris, the HTTPS version of the cwrcwriter can't make calls to the HTTPS versions of the entity sources (you may have noticed that with the https version of the gitwriter, wikidata was the only source returning results).  

So we should ideally switch our calls to the entity sources to instead use HTTPS.

Getty ULAN doesn't, however, appear to have an HTTPS version of their lookups.
DbPedia also doesn't seem to have HTTPS, although i have yet to confirm.
I think VIAF does, but I've yet to confirm by actually using it.

If we want to continue our non-http entity sources (at the very least that being Getty, but maybe also dbpedia) we could:

1.  Stop using https for the gitwriter.  the downside here is that communication with the gitserver won't be encrypted.  I still am not sure that that will affect the Github authentication since we use OAuth for that and the actual authentication with GitHub is done at the GitHub site (which uses https).  we do pass a GitHub token after OAuth, but it is encrypted as a jwt.  Again, we should clarify with Jeff what the risk is.  I can see that one risk that that the actual data in the document will be sent without encryption, but whether that is a problem I don't know.

2.  We could proxy the calls to the entities.  The downside being more server side code to maintain.

**Comment by SusanBrown** [comment]
I suggest that we consult first with @jefferya and then, depending on the outcome of that consultation, perhaps with external partners to hear how they would feel about not using https for gitwriter. I can think of a couple of people who would be easy to consult about this.

So perhaps we can consult with Jeff about this at our Tuesday checkin.

**Comment by jefferya** [comment]
Regarding James' note & number #2 , CWRC currently uses Apache HTTP reverse proxies. This would be about 4 lines for each linked-data source within the Apache config (in the context of CWRC, not sure about GitWriter).   

I'll response regards to my reasoning via e-mail, outside GitHub.

**Comment by jchartrand** [comment]
I'm assuming we want to setup proxies, so I've created another issue for that:

https://github.com/cwrc/CWRC-GitWriter/issues/10

**Comment by jchartrand** [comment]
Both prod (https://cwrc-writer.cwrc.ca) and dev (https://dev-cwrc-writer.cwrc.ca) should now be HTTPS only, using LetsEncrypt certificates.  Calls to HTTP should automatically redirect to HTTPS.  I also revoked any github tokens that had been granted from past authorizations, so everyone will have to reauthorize.

**Comment by ilovan** [comment]
Works as described. I will close it directly, as there is no code to push to prod at this point.
Correct me if I am wrong, @jchartrand
