### ISSUE TITLE
Handle http references in the processing instructions of documents upon loading into Git-Writer. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#7]
# Description:
When accessing a document that contains http references in its processing instructions, the https version of Git-Writer is unable to load the http references and fails to load the document properly:

<img width="358" alt="screen shot 2018-01-10 at 12 43 17 pm" src="https://user-images.githubusercontent.com/6600070/34792053-1940924e-f604-11e7-9a03-09ae25acbaef.png">
 
<img width="417" alt="screen shot 2018-01-10 at 12 43 08 pm" src="https://user-images.githubusercontent.com/6600070/34792103-3a13a45c-f604-11e7-9d3e-870ae4d9717b.png">

<img width="327" alt="screen shot 2018-01-10 at 12 43 27 pm" src="https://user-images.githubusercontent.com/6600070/34792124-478515f8-f604-11e7-881a-e89cc886edda.png">

> **NOTE:** this error affects http references in **processing instructions only** (http references within the body of the document should not cause any issues)

# Proposed solution: 

1. User attempts to open such a document
**Result:** Warning message pops up with the text:
> Selected document references non-secure (http) URLs in its processing instructions. To open it in the Writer, please modify the processing instructions to reference secure URLs OR switch to the http version of the GitWriter.(Choosing the later may expose your GitHub account to security breaches).

Ideally: warning message contains two buttons at the button: One that says _"Modify processing instructions"_ and one that says _"Switch to http Git-Writer"_ Each button does what it says, the former by opening the document in an "edit source" popup.

@jchartrand , can you let us know if the two buttons described could exist and determine the actions described?

@SusanBrown , please review and revise as needed.

**Comment by jchartrand** [comment]
This is really two issues:  

1. to detect http refs in css and schema urls in loaded docs and tell the user they can't therefore use the https version of the cwrcwriter but they can use the http version of the cwrcwriter, or change their refs.
2. to detect calls to the http version of the cwrcwriter and advise the user that they should instead use https if possible

Andrew is best to do the first.  I could do the second but if andrew is already doing the first he could probably more easily do the second as well.

**Comment by ilovan** [comment]
@jchartrand, No. 1 in your comment overlaps with the description/solution I proposed above. 
No. 2 has been moved to a new issue: https://github.com/cwrc/CWRC-GitWriter/issues/8

**Comment by jchartrand** [comment]
@ilovan you ask:  "@jchartrand , can you let us know if the two buttons described could exist and determine the actions described?"

Yes, the two buttons could exist.  I don't know what you mean by 'determine the actions described'.  If you meant something like  'can you let us know if the two buttons described could exist, and when pressed invoke the actions described' then:

1. Yes, the "Switch to http Git-Writer" button could redirect to the http version of the CWRC-Writer, although it might be hard to pass the text through the redirect - the user might have to reload the text again, after the redirect.  

2.  The "Modify processing instructions" could most likely open an edit source popup, but given how infrequently you'd expect this to occur (I think?), I'd suggest that instead of coding in this popup, which adds complexity, you just tell the user to edit it in a text editor on their local machine.

I also suggest that where you say "Choosing the later may expose your GitHub account to security breaches"  we should first be clear about what that security breach is, or might be.  I for one still don't know.  (note that 'later' should be 'latter').  I'd also suggest simplifying the text:

Your document has HTTP URLs in its processing instructions:

```To be more specific we could here show them the specific urls that they need to change.```

These URLS can't (because of browser security) be used with the HTTPS version of the CWRC-Writer.  Either change the URLs in your processing instructions to HTTPS, OR switch to the HTTP version of the CWRC-Writer.  The HTTP version of the GitWriter is, however, less secure.

Should this checking apply not just to the GitWriter, but also to the Islandora version (if it uses https)?

**Comment by SusanBrown** [comment]
We will use proxies instead for http entities.
